### ISSUE TITLE
No DUOME button in checkpoint test

### ISSUE THREAD

**Issue by eranb66** [lionel-rowe/duome-sentence-discussions#1]
### What went wrong?

I'm testing checkpoint #2 in the Russian tree. After answering the first challenge, there is a DISCUSS button but no DUOME button.

### Expected behavior

There should have been a DUOME button.

### Steps to reproduce

1. Register to Russian for English speakers. (I tried the same in the French tree and it doesn't occur there, I don't know what other trees have this problem other than Russian.)
2. Start the checkpoint #2 test. (I got a similar problem in checkpoint #1 too, but it behaved a bit differently, there was no DISCUSS button either.)
3. Answer the first challenge. (I got it right, not sure if that matters.)
4. You get the DISCUSS button but no DUOME button.

### Debug output

```shell
Couldn't paste it, it was too long. I attached it in a file below.
```

### Screenshots or other useful information

![2022-05-05 (1)](https://user-images.githubusercontent.com/105006449/166970858-2a2cec17-8e79-4aa4-a8a6-74dc64707e5a.png)
[debug output.txt](https://github.com/lionel-rowe/duome-sentence-discussions/files/8633226/debug.output.txt)

**Comment by lionel-rowe** [comment]
These challenge types should now be supported as of [v0.1.17](https://forum.duome.eu/ext/luoning/sentencediscussions/styles/all/theme/js/script.user.js). Closing for now, but let me know if the problem re-occurs with other checkpoint tests.
